### ISSUE TITLE
Certificate helper

### ISSUE THREAD

**Issue by alecgunny** [ML4GW/mldatafind#5]
Some of the relevant services for us like dqsegdb require setting up authentication. It might help to provide some wrappers around Duncan's [`ecp-get-cert`](https://github.com/duncanmmacleod/ciecplib/blob/fb8d786a11bc25e8ddfe19a90b2a091338481031/ciecplib/ui.py#L99) code that helps to automate this if a user doesn't have an up-to-date credential using some environment variables.

**Comment by EthanMarx** [comment]
Mocked up an idea in #6

**Comment by EthanMarx** [comment]
closes with #6
